name: Branch up-to-date
description: Checks if the current git branch is up to date with any other branch
author: https://github.com/HemanthGowda
requirements:
  - git
configuration:
  properties:
    remote:
      type: string
    branch:
      type: string
  additionalProperties: false
